square/java-code-styles

- configs/Square.xml
- configs/SquareAndroid.xml
Give a little breathing room, making `{1, 2, 3}` a little easier to read as `{ 1, 2, 3 }`.
> Add space within array initializer braces

- install.sh
If IDE's directory exist, but codestyles/ not, the script doesn't install styles.
In my opinion it should. To do that it need to create the codestyles/  directory.
> Add creating codestyles/ if not exist

- configs/SquareAndroid.xml
I propose "Wrap if long", as below:
```
int x =
(3 + 4 + 5 + 6) * (7 + 8 + 9
+ 10) * (11 + 12 + 13
+ 14 + 0xFFFFFFFF);
```
instead of
```
int x = (3 + 4 + 5 + 6) * (7
+ 8
+ 9
+ 10) * (11
+ 12
+ 13
+ 14
+ 0xFFFFFFFF);
```
*(above examples assume that line has max. 37 characters)*
> Removed the ridiculous chopping down of binary expressions

- configs/codestyles/SquareAndroid.xml
Fixed code style arrangement for XML files as per the discussion in [Issue#21](https://github.com/square/java-code-styles/issues/21).
> Added XML arrangement for SquareAndroid style

- configs/codestyles/SquareAndroid.xml
```xml
<FrameLayout
android:layout_width="match_parent"
android:layout_height="match_parent"/>
```
becomes
```xml
<FrameLayout
android:layout_width="match_parent"
android:layout_height="match_parent"
/>
```
which is much better for diffs and moving attributes up/down.
@edenman
> Ensure line-break after last attribute.

- configs/codestyles/SquareAndroid.xml
Rearranges  the `android:name` tag present in Manifest and AnimatedVectorDrawable files.
Default Formatting:
```
<target
android:animation="@animator/test" 
android:name="test" />
```
Updated:
```
<target
android:name="test"
android:animation="@animator/test" />
```
> Added XML code style to format android:name tag.

- install.sh
Output when running ./install.sh in zsh:
```
Installing Square IntelliJ configs...
/sq/java-code-styles/configs/codestyles/Square.xml -> /Users/jackdanger/Library/Preferences/IntelliJIdea12/codestyles/Square.xml
/sq/java-code-styles/configs/codestyles/SquareAndroid.xml -> /Users/jackdanger/Library/Preferences/IntelliJIdea12/codestyles/SquareAndroid.xml
/sq/java-code-styles/configs/inspection/Square.xml -> /Users/jackdanger/Library/Preferences/IntelliJIdea12/inspection/Square.xml
./install.sh: line 15: [: too many arguments
/sq/java-code-styles/configs/codestyles/Square.xml -> /Users/jackdanger/Library/Preferences/IdeaIC13/codestyles/Square.xml
/sq/java-code-styles/configs/codestyles/SquareAndroid.xml -> /Users/jackdanger/Library/Preferences/IdeaIC13/codestyles/SquareAndroid.xml …
```
> using double brackets for safety

- install.bat
If a Windows user has a space character in the username,
1. `userprofile` breaks into 2 variables and must be saved with `" "`.
2. `call :copy_config` is supplied with an argument but if there is a space in the argument value, it breaks into 2 arguments.
3. command `xcopy /s configs C:\Users\John Doe` is also supplied with 2 arguments because of the space character.
> Added support for usernames with spaces.

- configs/codestyles/Square.xml
- configs/codestyles/SquareAndroid.xml
- Applied the default settings from the Kotlin style guide using the new plugin with more formatting support.
- Tweaked the settings a bit to match our existing style better.
> New Kotlin formatting options

- configs/codestyles/Square.xml
- configs/codestyles/SquareAndroid.xml
These options haven't shown up before. I used Export from the settings dialog this time instead of just copying the file from the preferences directory.
> Make the Kotlin indent 2 spaces.

- configs/codestyles/Square.xml
Kotlin appears to have the default option of using star imports after N
imports of the same package. Turn that off.
> Do not use star imports

- configs/codestyles/SquareAndroid.xml
Analog to this setting:
Before:
After:
> Don't force align Groovy list and map literals

- install.sh
The same config files work for IntelliJ 2020.1, but the location has changed
so added that directory. Also quoting the variable derefences since the new
path contains a space and it doesn't work without it
> IntelliJ 2020.1 support

- configs/codestyles/Square.xml
- configs/codestyles/SquareAndroid.xml
The old setting used "Always wrap", the new setting uses "Chop down if long". The Java code style uses "Chop down if long", too.
The old setting made code harder to read in many scenarios:
```kotlin
// Old
assertThat(myList).containsExactly("a", "b", "c")
.inOrder()
// New
assertThat(myList).containsExactly("a", "b", "c").inOrder()
```
```kotlin
// Old
if (project.file("src/debug")
.exists() || project.file("src/release")
.exists()
) {
return
}
// New
if (project.file("src/debug").exists() || project.file("src/release").exists()) {
return
}
```
```kotlin
// Old
val string = "The project path is ${
project.path.substring(1)
.replace(':', '/')
}"
// New
val string = "The project path is ${project.path.substring(1).replace(':', '/')}"
```
```kotlin
// Old
stringList
.filter {..}
.map { …
```
> Stop always wrapping chained function calls in Kotlin. 

- install.sh
Update the install path for newer IntelliJ and Android Studio versions when using the JetBrains Toolbox.
This is similar to #76, but also includes IntelliJ.
> Update the install path

- configs/options/editor.codeinsight.xml
According to the Square Java style guide, we should prefer `javax.inject.Inject` for dependency injection: https://wiki.sqprod.co/pages/viewpage.action?pageId=14811784
This PR excludes the other two Inject options from IJ suggestions, enabling developers to auto-import the desired type after annotating a field or constructor with `@Inject`. The google one, at least, still seems to work fine, but there's no reason to prefer it, so we should stick with the style guide's recommendation and also eliminate the manual touchpoint of choosing an import from a list.
Another nice benefit of using the javax type is that IJ understands it, so it prevents the annoying "managed bean must have a constructor with no parameters, or a constructor annotated @Inject" error.
The `com.google.inject.Inject` …
> exclude wrong Inject types

- configs/codestyles/Square.xml
- configs/codestyles/SquareAndroid.xml
This PR is basically reopening #82. I merged the settings that IntelliJ and KtLint export.
> Track KtLint's code styles.

- configs/inspection/Square.xml
add ConstantConditions.SUGGEST_NULLABLE_ANNOTATIONS to inspections.
This inspection flags code that mixes @Nullable values and non-@Nullable params.
By Square Java convention, we treat unannotated method params as non-null by default.
Thus, code that mixes nullability in this way is likely incorrect, and creates an easy place for NPEs to hide.
With this change, a method call that passes a value IntelliJ determines to be possibly null into a method parameter not annotated as @Nullable will be highlighted with the warning text, `Argument '<some possibly-null expression>' might be null but passed to non-annotated parameter`.
> add SUGGEST_NULLABLE_ANNOTATIONS inspection

- configs/inspection/Square.xml
Opinion: property access should be used only if there are no side-effects. Assertions have side-effects.
The list of exclusions here are not exhaustive as there are too many subclasses. IntelliJ requires declaring the fully qualified classpath of all subclasses. It doesn't support declaring exclusions on the top-level interface or class.
> Exclude property access inspections on assertj assertions due to side-effects

- configs/codestyles/Square.xml
- configs/codestyles/SquareAndroid.xml
`ALLOW_TRAILING_COMMA` configuration does not currently get picked up by
IJ/AS, it only works if it's set up using legacy `JetCodeStyleSettings`
block. See https://youtrack.jetbrains.com/issue/KTIJ-22516 for more
details, enabling trailing commas via `JetCodeStyleSettings` until the
IDE bug is fixed.
> Fix trailing commas configuration - KTIJ-22516.
